[workspace]
authors = ["Julian RÃ¼th <julian.rueth@fsfe.org>"]
channels = ["conda-forge"]
name = "planar-maps-plot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
sagelib = ">=10.7,<11"
jupyterlab = ">=4.5.3,<5"
ipywidgets = ">=8.1.8,<9"

[pypi-dependencies]
ipymuvue = ">=0.6.0, <0.7"
